version: '3'
services:
  nginx-app:
    image: registry:5000/nginx
    ports:
      - "80:80"
    depends_on:
      - "rsyslog-agent"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"

  rsyslog-agent:
    image: registry:5000/rsyslog-agent
    ports:
      - "514:514/udp"
    environment:
      - LOG_SERVER=192.168.1.5

  rsyslog-server:
    image: registry:5000/rsyslog-server
    ports:
      - "514:514/udp"
